name: CI

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
      repo:
        required: true
        type: string
      args:
        required: false
        default: ""
        type: string
    secrets:
      token:
        required: true

jobs:
  ci:
    name: ${{ inputs.name }}
    runs-on:
      group: apple-silicon

    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ inputs.repo }}
      - run: echo "PATH=/opt/homebrew/bin:/opt/homebrew/sbin:$PATH" >> $GITHUB_ENV
      - name: Cirrus CI
        run: cirrus run --output github-actions --artifacts-dir artifacts ${{ inputs.args }}
