name: Binaries

on:
  workflow_call:
    inputs:
      repo:
        required: true
        type: string
      tag:
        required: true
        type: string
    secrets:
      token:
        required: true

jobs:
  build:
    name: build
    runs-on:
      group: apple-silicon

    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ inputs.repo }}

      - run: echo "PATH=/opt/homebrew/bin:/opt/homebrew/sbin:$PATH" >> $GITHUB_ENV
      - name: Cirrus CI
        run: cirrus run --artifacts-dir artifacts
      - name: Create Checksum
        run: |
          cd artifacts/Build/binary/burrito_out
          chmod +x ./*
          shasum -a 256 ./* > next_ls_checksums.txt
          cd ..
      - name: Upload to release
        env:
          GITHUB_TOKEN: ${{ secrets.token }}
        run: gh release upload ${{ inputs.tag }} artifacts/Build/binary/burrito_out/* --repo "${{ inputs.repo }}"
